title: "App ONEGOAL"
description: "Página informativa del repositorio"
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

# Configuración opcional
show_downloads: true
github:
  is_project_page: true
